# Generated by Django 4.2.1 on 2023-07-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FriendModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school', models.CharField(max_length=30)),
                ('section', models.CharField(max_length=30)),
                ('attendance', models.BooleanField()),
                ('cw', models.BooleanField()),
                ('hw', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='MeModel',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('proxyInheritApp.friendmodel',),
        ),
    ]
