# Generated by Django 4.2.1 on 2023-07-16 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('mobile', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('confirm_password', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('weight', models.IntegerField()),
                ('size', models.CharField(max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=3)),
                ('review', models.TextField(max_length=100)),
                ('youtube', models.BooleanField()),
                ('photo', models.FileField(upload_to='')),
            ],
        ),
    ]
