# Generated by Django 4.2.1 on 2023-07-16 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='student_info',
            new_name='Student',
        ),
    ]
