# Generated by Django 4.2.1 on 2023-07-16 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0003_rename_student_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Students',
            new_name='Contractors',
        ),
    ]
