# Generated by Django 4.2.3 on 2023-07-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_bookstoremodel_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Humor', 'Humor'), ('Sci-Fi', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller'), ('Horror', 'Horror')], max_length=30),
        ),
    ]
