# Generated by Django 4.2.3 on 2023-07-17 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_bookstoremodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Humor', 'Humor'), ('Sci-Fi', 'Sci-Fi'), ('Mystery', 'Mystery'), ('Horror', 'Horror'), ('Thriller', 'Thriller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_pub',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
