# Generated by Django 4.2.1 on 2023-07-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_alter_bookstoremodel_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Humor', 'Humor'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BookStoreModel',
        ),
    ]
