# Generated by Django 4.2.1 on 2023-07-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_alter_addbook_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addbook',
            name='category',
            field=models.CharField(choices=[('Humor', 'Humor'), ('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Drama', 'Drama'), ('Novel', 'Novel'), ('Mystery', 'Mystery'), ('Religious', 'Religious'), ('Computer Science', 'Computer Science'), ('Adventure', 'Adventure'), ('Poetry', 'Poetry'), ('Thriller', 'Thriller'), ('Comedy', 'Comedy')], max_length=30),
        ),
    ]
