# Generated by Django 4.2.3 on 2023-07-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='category',
            field=models.CharField(choices=[('Horror', 'Horror'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Mystery', 'Mystery'), ('Thriller', 'Thriller')], max_length=30),
        ),
        migrations.AlterField(
            model_name='bookstoremodel',
            name='last_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
