# Generated by Django 4.2.1 on 2023-07-19 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_add_book_delete_bookstoremodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('category', models.CharField(choices=[('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Thriller', 'Thriller'), ('Mystery', 'Mystery'), ('Horror', 'Horror')], max_length=30)),
                ('first_pub', models.DateTimeField(auto_now_add=True)),
                ('last_pub', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='add_book',
        ),
    ]
