# Generated by Django 4.2.1 on 2023-07-25 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_courseinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseinfo',
            old_name='credits',
            new_name='marks',
        ),
    ]
